#!/bin/bash
sudo apt -y install git
cd /root/
sudo git clone https://github.com/dannylanda/wordpress-project.git
chmod -R 755 wordpress-project #everything for root read and execute for everthing else
sudo bash wordpress-project/lemp-setup.sh
